let vector = Vector.createVector(-1.4, 5)
let vector2 = Vector.createVector(4.6, 8)
Vector.vectorAdd(vector, vector2).printVector()
Vector.vectorSub(vector, vector2).printVector()
Vector.vectorMultiplication(vector, vector2).printVector()
console.log(Vector.dotProduct(vector, vector2))
console.log(Vector.euclideanDistance(vector, vector2))
console.log(vector.vectorMagnitude())
vector.vectorScale(5)
vector.printVector()
