let vector = Vector.create(-1.4, 5)
let vector2 = Vector.create(4.6, 8)
console.log(Vector.add(vector, vector2).toString())
console.log(Vector.sub(vector, vector2).toString())
console.log(Vector.multiplication(vector, vector2).toString())
console.log(Vector.dotProduct(vector, vector2))
console.log(Vector.euclideanDistance(vector, vector2))
console.log(vector.magnitude())
vector.scale(5)
console.log(vector.toString())
